### ISSUE TITLE
Add an instance of MonadDB for Eff

### ISSUE THREAD

**Issue by arybczak** [3kyro/hpqtypes-effectful#17]
Hey,

Thanks for writing the adapter 🙂 I see it's rewriting methods of the typeclass instead of implementing them via the effect though.

For how it should be done please see https://github.com/haskell-effectful/crypto-rng-effectful/pull/3.

If you provide the MonadDB instance and delegate to the effect, then all functions requiring the constraint will "just work" with the Eff monad. You will also not need qualified imports because there will be no name clashes.

**Comment by kawu** [comment]
Nice, thanks for the hint @arybczak!  Reusing the DBT's MonadDB instance is what we originally wanted to do but failed.  We will give it another try :).

**Comment by arybczak** [comment]
Ah, but this isn't about reusing the instance for DBT (I don't think you can do that).

The problem you have right now is that when you're inside the `EffectDB :> es => Eff es`, you can't use any of the functions from `hpqtypes` such as `runQuery_`, `fetchOne` etc. because they require an instance of `MonadDB`, but you didn't provide such instance for `Eff es`. I'm sure you've noticed that since you added rewrites of `foldrDB` etc., but that approach doesn't scale, you'd have to rewrite everything.

You need to, instead of writing top-level functions `runQuery` etc., write this (canonical, orphan) instance:

```haskell
instance EffectDB :> es => MonadDB (Eff es) where
  runQuery = send . RunQuery
  ...
```

just like I did in the PR I linked. Then:

1. All already-written functions that  require `MonadDB` will work in `Eff es` if it has the `EffectDB` in its stack, so your rewrites of `foldrDB`, `foldlDB` etc. aren't needed.
2. You will no longer need to import `Effectful.HPQTypes` qualified because it will no longer have functions that clash with the ones from `hpqtypes`.

**Comment by kawu** [comment]
> Ah, but this isn't about reusing the instance for DBT (I don't think you can do that).

Right, I hoped we could, but I don't see how that could be done for "higher-order commands" (e.g. `withNewConnection`).

> The problem you have right now is that when you're inside the EffectDB :> es => Eff es, you can't use any of the functions from hpqtypes

Got it :+1:
